ci:
  # TODO: Run pyright in pre-commit.ci once there's resolution on https://github.com/pre-commit-ci/issues/issues/13
  skip: [pyright]
  autoupdate_commit_msg: 'chore(pre-commit): pre-commit autoupdate'
repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-bugbear==22.1.11']
- repo: local
  hooks:
  - id: pyright
    name: pyright
    entry: pyright
    types: [python]
    language: system

exclude: migrations
