repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.19.4
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.5.0
  hooks:
  - id: reorder-python-imports
    args: ["--application-directories", "bot:lib"]
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-bugbear==21.3.2']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
  - id: mypy

exclude: migrations
