repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.8.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-bugbear==20.1.4']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
  - id: mypy

exclude: migrations
