repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
- repo: https://github.com/ambv/black
  rev: 21.12b0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-bugbear==21.3.2']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.930
  hooks:
  - id: mypy

exclude: migrations
