[tool.black]
line-length = 90
target-version = ['py38']

[tool.semantic_release]
version_variable = "bot.py:__version__"
upload_to_pypi = false
upload_to_release = false
build_command = ""
remove_dist = false
