"""add guild announcements

Revision ID: 1354450daa32
Revises: beec26d674fd
Create Date: 2022-01-19 18:59:49.239486

"""
from alembic import op
import sqlalchemy as sa
import bot


# revision identifiers, used by Alembic.
revision = "1354450daa32"
down_revision = "beec26d674fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_announcements",
        sa.Column("guild_id", sa.BIGINT(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("created_at", bot.database.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"], ["guild_settings.guild_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("guild_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guild_announcements")
    # ### end Alembic commands ###
