"""add scheduled_events

Revision ID: 16e3c8b20c26
Revises: ad375ea654d5
Create Date: 2021-12-31 10:29:54.135898

"""
from alembic import op
import sqlalchemy as sa
import bot


# revision identifiers, used by Alembic.
revision = "16e3c8b20c26"
down_revision = "ad375ea654d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_events",
        sa.Column("event_id", sa.BIGINT(), nullable=False),
        sa.Column("created_by", sa.BIGINT(), nullable=True),
        sa.Column("created_at", bot.database.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_scheduled_events_created_by"),
        "scheduled_events",
        ["created_by"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_events_created_by"), table_name="scheduled_events")
    op.drop_table("scheduled_events")
    # ### end Alembic commands ###
