"""add star tables

Revision ID: 273609b17e5b
Revises: 697c0fc1f5a6
Create Date: 2022-02-20 19:13:49.695248

"""
from alembic import op
import sqlalchemy as sa
import bot
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "273609b17e5b"
down_revision = "697c0fc1f5a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "star_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("from_user_id", sa.BIGINT(), nullable=True),
        sa.Column("to_user_id", sa.BIGINT(), nullable=True),
        sa.Column("message_id", sa.BIGINT(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("created_at", bot.database.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_stars",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("star_count", sa.Integer(), nullable=True),
        sa.Column("created_at", bot.database.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", bot.database.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_stars")
    op.drop_table("star_logs")
    # ### end Alembic commands ###
