"""add zoom_meetings setup_at

Revision ID: 37a124b0099b
Revises: 5802c6bd278a
Create Date: 2021-03-03 23:50:19.172972

"""
from alembic import op
import sqlalchemy as sa
from bot import database


# revision identifiers, used by Alembic.
revision = "37a124b0099b"
down_revision = "5802c6bd278a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "zoom_meetings",
        sa.Column("setup_at", database.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("zoom_meetings", "setup_at")
    # ### end Alembic commands ###
