"""add zoom tables

Revision ID: 38ed74370165
Revises: 68fd5a25595c
Create Date: 2021-02-07 12:45:12.118157

"""
from alembic import op
import sqlalchemy as sa
from bot import database


# revision identifiers, used by Alembic.
revision = "38ed74370165"
down_revision = "68fd5a25595c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zoom_meetings",
        sa.Column("meeting_id", sa.BIGINT(), nullable=False),
        sa.Column("zoom_user", sa.Text(), nullable=False),
        sa.Column("join_url", sa.Text(), nullable=False),
        sa.Column("passcode", sa.Text(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("created_at", database.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("meeting_id"),
    )
    op.create_table(
        "zoom_messages",
        sa.Column("message_id", sa.BIGINT(), nullable=False),
        sa.Column("channel_id", sa.BIGINT(), nullable=False),
        sa.Column("meeting_id", sa.BIGINT(), nullable=True),
        sa.Column("created_at", database.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"], ["zoom_meetings.meeting_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_table(
        "zoom_participants",
        sa.Column("meeting_id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("joined_at", database.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["meeting_id"], ["zoom_meetings.meeting_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("meeting_id", "name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("zoom_participants")
    op.drop_table("zoom_messages")
    op.drop_table("zoom_meetings")
    # ### end Alembic commands ###
