"""add include_scheduled_events

Revision ID: 3e378f3d6bf5
Revises: 1354450daa32
Create Date: 2022-01-23 13:44:48.660909

"""
from alembic import op
import sqlalchemy as sa
import bot


# revision identifiers, used by Alembic.
revision = "3e378f3d6bf5"
down_revision = "1354450daa32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guild_settings",
        sa.Column(
            "include_scheduled_events",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guild_settings", "include_scheduled_events")
    # ### end Alembic commands ###
