"""update aslpp_members

Revision ID: 523a52c7369c
Revises: 16e3c8b20c26
Create Date: 2022-01-01 17:22:31.854043

"""
from alembic import op
import sqlalchemy as sa
import bot
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "523a52c7369c"
down_revision = "16e3c8b20c26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("aslpp_members", sa.Column("roles", sa.Text(), nullable=True))
    op.drop_column("aslpp_members", "last_message_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "aslpp_members",
        sa.Column(
            "last_message_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("aslpp_members", "roles")
    # ### end Alembic commands ###
