"""Add is_active

Revision ID: 60ad67ade014
Revises: dad312a509df
Create Date: 2021-04-15 22:22:24.073176

"""
from alembic import op
import sqlalchemy as sa
import bot


# revision identifiers, used by Alembic.
revision = "60ad67ade014"
down_revision = "dad312a509df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "aslpp_members",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aslpp_members", "is_active")
    # ### end Alembic commands ###
