"""remove topics

Revision ID: 68fd5a25595c
Revises: b1014cab80a9
Create Date: 2020-11-25 20:37:52.464861

"""
from alembic import op
import sqlalchemy as sa
from bot import database
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "68fd5a25595c"
down_revision = "b1014cab80a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("topic_usages")
    op.drop_table("topics")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic_usages",
        sa.Column("guild_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("topic_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "last_used_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name="topic_usages_topic_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("guild_id", "topic_id", name="topic_usages_pkey"),
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="topics_pkey"),
        sa.UniqueConstraint("content", name="topics_content_key"),
    )
    # ### end Alembic commands ###
