"""add include_wordle

Revision ID: 697c0fc1f5a6
Revises: 3e378f3d6bf5
Create Date: 2022-01-27 00:05:22.525528

"""
from alembic import op
import sqlalchemy as sa
import bot


# revision identifiers, used by Alembic.
revision = "697c0fc1f5a6"
down_revision = "3e378f3d6bf5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guild_settings",
        sa.Column(
            "include_wordle",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guild_settings", "include_wordle")
    # ### end Alembic commands ###
