"""create tables

Revision ID: a429443e6c16
Revises: 
Create Date: 2020-11-11 23:35:45.046234

"""
from alembic import op
import sqlalchemy as sa
from bot import database


# revision identifiers, used by Alembic.
revision = "a429443e6c16"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("timezone", database.TimeZone(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_settings")
    # ### end Alembic commands ###
