"""add verified_role_ids

Revision ID: acd3a66644a2
Revises: 273609b17e5b
Create Date: 2022-02-21 10:33:27.590050

"""
from alembic import op
import sqlalchemy as sa
import bot
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "acd3a66644a2"
down_revision = "273609b17e5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guild_settings",
        sa.Column(
            "verified_role_ids",
            postgresql.ARRAY(sa.BIGINT()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guild_settings", "verified_role_ids")
    # ### end Alembic commands ###
