"""add host columns

Revision ID: c56a6b9d6e85
Revises: 38ed74370165
Create Date: 2021-02-20 13:24:29.082634

"""
from alembic import op
import sqlalchemy as sa
from bot import database


# revision identifiers, used by Alembic.
revision = "c56a6b9d6e85"
down_revision = "38ed74370165"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("zoom_meetings", sa.Column("host_id", sa.Text(), nullable=True))
    op.add_column("zoom_participants", sa.Column("zoom_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("zoom_participants", "zoom_id")
    op.drop_column("zoom_meetings", "host_id")
    # ### end Alembic commands ###
