"""Add aslpp tables

Revision ID: dad312a509df
Revises: df8d4e9e1c2e
Create Date: 2021-04-15 13:30:04.714133

"""
from alembic import op
import sqlalchemy as sa
import bot


# revision identifiers, used by Alembic.
revision = "dad312a509df"
down_revision = "df8d4e9e1c2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aslpp_intros",
        sa.Column("message_id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("posted_at", bot.database.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_at", bot.database.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_index(
        op.f("ix_aslpp_intros_user_id"), "aslpp_intros", ["user_id"], unique=False
    )
    op.create_table(
        "aslpp_members",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("joined_at", bot.database.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "last_message_at", bot.database.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column("created_at", bot.database.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("aslpp_members")
    op.drop_index(op.f("ix_aslpp_intros_user_id"), table_name="aslpp_intros")
    op.drop_table("aslpp_intros")
    # ### end Alembic commands ###
