"""Add zzzzoom meetings

Revision ID: df8d4e9e1c2e
Revises: 816ea3631582
Create Date: 2021-03-21 19:01:14.653939

"""
import sqlalchemy as sa
from alembic import op

import bot

# revision identifiers, used by Alembic.
revision = "df8d4e9e1c2e"
down_revision = "816ea3631582"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zzzzoom_meetings",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("meeting_id", sa.BIGINT(), nullable=True),
        sa.Column("created_at", bot.database.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"], ["zoom_meetings.meeting_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_zzzzoom_meetings_meeting_id"),
        "zzzzoom_meetings",
        ["meeting_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_zzzzoom_meetings_meeting_id"), table_name="zzzzoom_meetings")
    op.drop_table("zzzzoom_meetings")
    # ### end Alembic commands ###
