"""add aslpp_members.has_acknowledged_rules

Revision ID: f4eff610ab27
Revises: 523a52c7369c
Create Date: 2022-01-01 22:23:02.792130

"""
from alembic import op
import sqlalchemy as sa
import bot


# revision identifiers, used by Alembic.
revision = "f4eff610ab27"
down_revision = "523a52c7369c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "aslpp_members",
        sa.Column(
            "has_acknowledged_rules",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aslpp_members", "has_acknowledged_rules")
    # ### end Alembic commands ###
