#!/bin/sh
# Based on conventions from https://github.com/github/scripts-to-rule-them-all
# script/update: Update application to run for its current checkout.
set -e

if [ -z "$SKIP_BOOTSTRAP" ]; then
  ./script/bootstrap
fi

if [ -n "$DB_RESET" ]; then
  echo "==> Recreating database"
  PYTHONPATH=. ./script/reset_db.py
fi

echo "==> Running migrations"
PYTHONPATH=. alembic upgrade head

echo "==> Syncing topics"
PYTHONPATH=. ./script/sync_topics.py

echo "==> Update finished."
